### ISSUE TITLE
Possible regression caused by switch to relative paths

### ISSUE THREAD

**Issue by rmg** [substack/insert-module-globals#55]
There was a lot of activity on strongloop/strong-mesh-client#40 starting just 10 hours after v6.6.1 was released.

Given that all the reports have been on Windows and I haven't been able to reproduce the problem on Mac or Linux, I'm beginning to suspect #54 introduced a Windows specific regression.

**Comment by parshap** [comment]
Yes, you're right. #54 introduced a Windows bug by using `path.relative` to generate paths used in `require()` calls which, on Windows, will use `\` as the path separator which is incompatible with `require()`. This needs to be changed to use `path.posix.relative`. I will send a pr when I have wifi if someone doesn't beat me to it.

**Comment by afandria** [comment]
I'm getting an error (Linux and Darwin) saying that `path.posix` is undefined. When `path.posix` is undefined, instead of `path.posix.relative(...)`, can the code fallback to `path.relative(...)`?

**Comment by rmg** [comment]
Oops, looks like `path.posix` was a 0.12 feature (0.11.15+).
