### ISSUE TITLE
Doesn't work with Windows paths.

### ISSUE THREAD

**Issue by Codes4Fun** [substack/insert-module-globals#59]
I was getting errors on windows using browserify that it could not find 'is-buffer' modules file. Looking at the issue I found that the getRelativeRequirePath function was adding './' to the path since the root started like this 'C:\Users'. So I made this change to work around it that checks if there is a colon:

```javascript
function getRelativeRequirePath(fullPath, fromPath) {
  var relpath = path.relative(path.dirname(fromPath), fullPath);
  if (relpath[0] !== "." && relpath[0] !== "/" && relpath[1] != ":") {
    relpath = "./" + relpath;
  }
  return relpath.replace(/\\/g, '/');
}
```

I was able to successfully browserify and test several modules after this, like typeforce and buffer-equals and dependents.

**Comment by zertosh** [comment]
I understand that windows full paths start with a letter followed by a colon, but under what circumstances would `relpath` look like that? What values of `fullPath` and `fromPath` cause that? (if they're on different drives?)

**Comment by parshap** [comment]
> under what circumstances would `relpath` look like that? What values of `fullPath` and `fromPath` cause that? (if they're on different drives?)

It will happen if the two paths don't have any common ancestors. For example:

```
> path.resolve("/src/app", "/usr/local/lib/node_modules/is-buffer/index.js")
'/usr/local/lib/node_modules/is-buffer/index.js'
```

On Windows this would result in something like `C:\usr\...`.

What's needed is a better way to determine if the resulting require path needs `./` prepended to it and I think I have a solution by using `path.dirname`. Will attempt it and send a pr if successful.

**Comment by zertosh** [comment]
> It will happen if the two paths don't have any common ancestors.

Got it. 

> hat's needed is a better way to determine if the resulting require path needs ./ prepended to it and I think I have a solution by using path.dirname. Will attempt it and send a pr if successful.

What if you just `path.join('./', path.relative(path.dirname(fromPath), fullPath))`?

**Comment by parshap** [comment]
> What if you just `path.join('./', path.relative(path.dirname(fromPath), fullPath))`?

I don't think that will work because we'd need this case to result in `'./index.js'`:

```
> path.join("./", "index.js")
'index.js'
```
