### ISSUE TITLE
Using with browserify

### ISSUE THREAD

**Issue by kuraga** [substack/insert-module-globals#64]
Good day, @substack !

How do I use it with Browserify? I don't see it in docs...

Thanks.

**Comment by parshap** [comment]
Browserify uses *insert-module-globals* directly (to insert globlals e.g., `process`) and exposes a hook to add your own variables with the `opts.insertGlobalVars` option. 

Alternatively you can use this module as a browserify transform.

**Comment by kuraga** [comment]
Thanks.
